version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "requirements.txt" }}
#            # fallback to using the latest cache if no exact match is found
#            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo pip install --upgrade pipenv
            pipenv install --skip-lock --dev

#      - save_cache:
#          paths:
#            - ./venv
#          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: tox
          command: pipenv run tox -e py37
